name: "Hello Actions"
description: "Great someone"
author: "2044smile@naver.com"

inputs:
  MY_NAME:
    description: "Who to great"
    required: true
    default: "World"
    
runs:
  using: "docker"
  image: "Dockerfile"
    
branding:
  icon: "mic"
  color: "purple"
